In [1]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
np.random.seed(42)

In [3]:
num_records = 1000

In [4]:
synthetic_df = pd.DataFrame({
    "Booking_ID": range(1, num_records + 1),

    "Hotel_Type": np.random.choice(
        ["City Hotel", "Resort Hotel"],
        num_records
    ),

    "Season": np.random.choice(
        ["Peak", "Off-Peak", "Holiday"],
        num_records
    ),

    "Rooms_Available": np.random.randint(
        10, 200, num_records
    ),

    "Base_Price": np.random.randint(
        50, 300, num_records
    ),

    "Demand_Level": np.random.choice(
        ["Low", "Medium", "High"],
        num_records
    ),

    "Booking_Probability": np.round(
        np.random.uniform(0.2, 1.0, num_records),
        2
    )
})

In [8]:
price_multiplier = np.random.uniform(0.8, 1.5, num_records)

synthetic_df["Dynamic_Price"] = (
    synthetic_df["Base_Price"] * price_multiplier
).round(2)

synthetic_df.head()

,Booking_ID,Hotel_Type,Season,Rooms_Available,Base_Price,Demand_Level,Booking_Probability,Dynamic_Price
0,1,City Hotel,Off-Peak,37,229,Low,0.60,234.10
1,2,Resort Hotel,Holiday,90,192,Low,0.76,188.46
2,3,City Hotel,Peak,123,260,High,0.63,223.94
3,4,City Hotel,Peak,49,184,Low,0.63,158.78
4,5,City Hotel,Peak,54,292,Low,0.54,273.10

In [9]:
synthetic_df["Revenue"] = (
    synthetic_df["Dynamic_Price"] *
    synthetic_df["Booking_Probability"]
).round(2)

In [6]:
synthetic_df.columns

Index(['Booking_ID', 'Hotel_Type', 'Season', 'Rooms_Available', 'Base_Price',
       'Demand_Level', 'Booking_Probability'],
      dtype='object')

In [10]:
synthetic_df.head()

,Booking_ID,Hotel_Type,Season,Rooms_Available,Base_Price,Demand_Level,Booking_Probability,Dynamic_Price,Revenue
0,1,City Hotel,Off-Peak,37,229,Low,0.60,234.10,140.46
1,2,Resort Hotel,Holiday,90,192,Low,0.76,188.46,143.23
2,3,City Hotel,Peak,123,260,High,0.63,223.94,141.08
3,4,City Hotel,Peak,49,184,Low,0.63,158.78,100.03
4,5,City Hotel,Peak,54,292,Low,0.54,273.10,147.47

In [11]:
synthetic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Booking_ID           1000 non-null   int64
 1   Hotel_Type           1000 non-null   object
 2   Season               1000 non-null   object
 3   Rooms_Available      1000 non-null   int64
 4   Base_Price           1000 non-null   int64
 5   Demand_Level         1000 non-null   object
 6   Booking_Probability  1000 non-null   float64
 7   Dynamic_Price        1000 non-null   float64
 8   Revenue              1000 non-null   float64
dtypes: float64(3), int64(3), object(3)
memory usage: 70.4+ KB

In [12]:
synthetic_df.isnull().sum()

Booking_ID             0
Hotel_Type             0
Season                 0
Rooms_Available        0
Base_Price             0
Demand_Level           0
Booking_Probability    0
Dynamic_Price          0
Revenue                0
dtype: int64

In [13]:
synthetic_df.to_csv(
    "synthetic_booking_data.csv",
    index=False
)

print("Synthetic dataset saved successfully!")

Synthetic dataset saved successfully!